## NumpPy

NumPy is a foundational open source python library for scientific computing. 
It provides high performance, multidimensional array objects and massive collection of tools for working with them. 
Like:
- Linear Algebra
- Fourier Transforms
- Statistics

Pandas, Matplotlib, Scikit-learn, TensorFLow/PyTorch are built on the top of the Numpy.


In [1]:
# import numpy library for numerical operations. we can use it to create arrays, perform mathematical operations, and more.
import numpy as np

In [2]:
np.__version__

'2.2.6'

## Creating NumPy Array

NumPy Array is also know as ndarray.
It is a powerful N-Dimensional gride of values used for numerical and scientific computing in python.
It has characteristics: Homogeneity, Fixed Size, Performance, etc.
NumPy Array Attributes:
 - ndim --> The number of dimensions in rank.
 - shape --> A tuple representing the size of each dimension (Rows & Columns)
 - size --> The total number of elements in the Array.
 - dtype --> The data types of elements (int64, float32)

In [3]:
list1 = [1, 2, 3, 4, 5]
print(list1)

[1, 2, 3, 4, 5]


In [4]:
# we can convert a list to a numpy array using the np.array() function. 
# This allows us to perform various operations on the array efficiently.

array1 = np.array(list1)
print(type(array1))
print(len(array1))
print(array1)

<class 'numpy.ndarray'>
5
[1 2 3 4 5]


In [5]:
# shape of the array use to total number of rows and columns in the array
array1.shape

(5,)

In [6]:
# ndim is use to find the number of dimensions in the array
array1.ndim

1

In [7]:
# we can also create a 2D array (matrix) using a list of lists. Each inner list represents a row in the matrix.
list2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]

]
print(list2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [8]:
# we can convert the list of lists to a 2D numpy array using the np.array() function. 
# This will create a 2D array (matrix) where each inner list becomes a row in the matrix.
array2 = np.array(list2)
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
# shape of the 2D array will give us the number of rows and columns in the matrix. 
# In this case, it will return (2, 4) which means there are 2 rows and 4 columns in the array.
array2.shape

(2, 4)

In [10]:
# ndim is used to find the number of dimensions in the array
array2.ndim

2

## Numpy array methods:
first import numpy as np
 - np.array() --> converts a list or tuple into an array
 - np.zeros() --> creates an array filled with zeros
 - np.ones() --> create an array filled with ones
 - np.arange() --> crate an array with a range of values 
 - np.linspace() --> evenly spaced numbers over an interval
 - array(): Creates NumPy arrays from Python lists
 - full(): Creates an array with all elements initialized to same user-specified value
 - diag(): Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
 - eye(): Creates NumPy array with ones on the diagonal and zeros elsewhere
 - identity(): Creates an identity matrix
 - random.rand(): Creates NumPy array of random numbers sampled from a uniform distribution


In [11]:
# we can also create arrays filled with zeros using the np.zeros() function. 
# This function takes the shape of the array as an argument and returns an array filled with zeros
np.zeros(shape=(2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [12]:
# we can create a 3D array (tensor) using a list of lists of lists. 
# Each inner list represents a 2D array (matrix) in the tensor.
np.zeros(shape=(3,4,4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [13]:
# we can also create arrays filled with a specific value using the np.full() function.
np.full(shape=(4,5), fill_value=2_00)

array([[200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200]])

In [14]:
# arrange is use to create a sequence of numbers in the array (start, stop, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [15]:
# we can also create an array of random numbers using the np.random.rand() function.
import random
random.randint(1,50)

46

In [16]:
# we can also create an array of random integers using the np.random.randint() function.
# It is use to generate random integeers between a specified range (low, high) in array format.

np.random.randint(1, 50)

34

In [17]:
# we can also create a 2D array of random integers using the np.random.randint() function by specifying the size of the array.
np.random.randint(1,50, size =(2,3))

array([[31, 39, 10],
       [37, 19, 12]])

## Accessing an Array
Indexing and Slicing NumPy Arrays
NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.
- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

OR

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]

Slicing:
Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [18]:
# 1D array
a = np.array([1,2,3,4,5])

In [19]:
# we can access elements in the array using indexing.
a[-3]

np.int64(3)

In [20]:
# we can also access a range of elements in the array using slicing.
# slicing syntax is [start:stop:step]. If we omit start, it defaults to the beginning of the array. If we omit stop, it defaults to the end of the array. If we omit step, it defaults to 1.
a[:3:]

array([1, 2, 3])

In [21]:
# 2D array
b = np.random.randint(0, 20, size=(3, 4))
b

array([[14, 11,  9,  3],
       [ 3, 14, 18, 16],
       [18,  2,  8,  8]])

In [22]:
# we can access elements in a 2D array using row and column indices. 
# The syntax is array[row_index, column_index].
b[1,0]

np.int64(3)

In [23]:
# we can also access the last element in the array using negative indexing.
b[-1, -1]

np.int64(8)

In [24]:
# we can also access elements in the array using negative indexing.
b[-3]

array([14, 11,  9,  3])

In [25]:
# Slicing 2D Array
# Syntax: array[row_start:row_stop:row_step, column_start:column_stop:column_step]
b[0::2, 2::]

array([[9, 3],
       [8, 8]])

In [26]:
# Syntax: array[row_start:row_stop:row_step, column_start:column_stop:column_step]
b[:2, 1]

array([11, 14])

In [27]:
# 3D array (tensor)
# syntax: np.random.randint(low, high, size=(block of array, rows, columns))
c = np.random.randint(0, 20, size=(3, 3, 4))
c

array([[[17,  2,  8,  8],
        [13,  9, 14, 10],
        [ 3,  0, 10,  3]],

       [[13,  6,  8,  2],
        [10,  6,  5, 10],
        [13,  5, 18, 11]],

       [[19, 15, 18,  1],
        [12, 11, 19,  9],
        [12,  2, 16, 15]]])

In [28]:
# we can access elements in a 3D array using three indices: block index, row index, and column index.
c[0,1,2]

np.int64(14)

In [29]:
# 20 colorful images
# Syntax: np.random.randint(low, high, size=(number of images, color channels, height, width))
d = np.random.randint(0, 20, size=(20, 3, 10, 10))
d

array([[[[10, 18, 17, ..., 14,  6, 15],
         [11,  2, 10, ..., 17, 19, 18],
         [19, 17, 19, ..., 17,  7,  0],
         ...,
         [19,  0, 15, ..., 10, 14, 11],
         [ 0,  6, 11, ..., 15,  9,  1],
         [18, 10, 16, ..., 16, 17, 16]],

        [[ 4,  7, 15, ..., 18, 17, 14],
         [ 5, 12,  6, ...,  3, 19, 16],
         [ 8,  1, 18, ...,  0,  6, 11],
         ...,
         [ 1,  4, 11, ..., 18, 10, 14],
         [ 6,  3, 19, ..., 14, 16, 15],
         [18, 11,  2, ...,  9, 14,  7]],

        [[ 5, 16,  4, ..., 11,  3,  6],
         [13,  0,  0, ..., 18,  1,  4],
         [16,  4,  6, ..., 18, 12,  4],
         ...,
         [ 5, 14, 17, ..., 15, 18, 19],
         [19, 11,  7, ...,  3, 10, 10],
         [10, 19, 16, ..., 14, 18, 17]]],


       [[[ 3, 12,  9, ...,  7, 12,  6],
         [ 7, 19,  0, ...,  3, 15, 14],
         [18, 10, 16, ...,  5, 19,  1],
         ...,
         [12, 18, 14, ...,  8, 10, 18],
         [19,  7, 14, ..., 19,  1, 19],
         [15, 14

In [30]:
# d[-1] will give us the last image in the array, 
# which is a 3D array of shape (3, 10, 10) representing the color channels and dimensions of the image.
d[-1]

array([[[13, 16, 15,  5, 15,  9,  4, 16, 17, 10],
        [10, 17,  5,  3, 15, 10,  8,  0, 12, 16],
        [18, 14, 11,  7,  0, 18, 18, 16,  5, 15],
        [19, 12, 15,  5,  6, 10,  7,  8,  8, 11],
        [12, 11, 17, 15, 15,  5,  3, 19, 19, 19],
        [ 5,  5,  8, 19, 10,  4,  1, 16,  7, 19],
        [ 3,  9, 14, 13, 10,  7,  9,  7, 10, 13],
        [13,  0,  9,  0,  4, 12, 17, 17,  2, 12],
        [13,  6, 11, 17, 13, 12,  1, 14, 13, 15],
        [ 4, 15,  1,  0, 10,  6, 13,  5,  5,  6]],

       [[12, 16, 12, 15, 11,  5,  0, 15, 10,  5],
        [ 8,  8,  7,  9, 15, 12, 15, 11,  3, 12],
        [11,  9, 12, 15, 10,  9,  7, 14,  5,  2],
        [ 1, 15, 10,  9,  2, 19,  7,  1,  9, 17],
        [ 6, 19,  2, 14,  6, 17, 18, 18,  0,  9],
        [12, 12,  6, 14, 15,  9,  8,  9,  3, 17],
        [11,  3, 17, 18, 11, 16,  0, 13,  1,  7],
        [10, 11,  5,  2,  0, 13, 14, 10, 10,  1],
        [ 0, 16, 19, 14, 16,  0, 12, 13,  8, 18],
        [ 7, 19, 11,  6,  0,  0, 13,  6,  9, 11]

In [31]:
c.shape

(3, 3, 4)