🔹 1. Array Creation Methods

Used to create NumPy arrays:

 - np.array() → create array from list

 - np.zeros() → array filled with 0

 - np.ones() → array filled with 1

 - np.arange() → range of values

 - np.linspace() → evenly spaced values

 - np.random.rand() → random numbers

🔹 2. Shape & Reshaping Methods

Control array structure:

 - arr.shape → get dimensions

 - arr.reshape() → change shape

 - arr.flatten() → convert to 1D

 - arr.T → transpose

🔹 3. Mathematical Operations

Perform calculations:

np.add(), np.subtract(), np.multiply(), np.divide()
np.sqrt(), np.power()
np.sum(), np.mean(), np.std()

🔹 4. Indexing & Slicing

Access elements:

 - arr[i] → single element

 - arr[start:end] → slicing

 - arr[:, 1] → column selection

🔹 5. Aggregation Methods

Summarize data:

 - arr.sum() → total

 - arr.min(), arr.max()

 - arr.argmax(), arr.argmin()

🔹 6. Joining & Splitting

Combine or break arrays:

 - np.concatenate()

 - np.vstack(), np.hstack()

 - np.split()

🔹 7. Sorting & Searching

 - np.sort() → sort array

 - np.where() → find condition

 - np.unique() → unique values

🔹 8. Copy & View

 - arr.copy() → new independent array

 - arr.view() → reference to original


In [488]:
import numpy as np

In [489]:
# Create a 3x4 array of random numbers
arr = np.random.rand(3, 4)
arr

array([[0.78317157, 0.03008433, 0.98072138, 0.45680695],
       [0.43554161, 0.72259951, 0.62326802, 0.04192128],
       [0.11263627, 0.59325786, 0.93496781, 0.72024262]])

In [490]:
# .shape - returns a tuple of the dimensions of the array
arr.shape

(3, 4)

In [491]:
# .ndim - returns the number of dimensions of the array
arr.ndim

2

In [492]:
# .dtype - returns the data type of the array
arr.dtype

dtype('float64')

In [493]:
# .size - returns the total number of elements in the array
arr.size

12

In [494]:
# Transpose of an array
arr_T = arr.T
arr_T.shape

(4, 3)

In [495]:
# Create a 3x4 array of random integers between 2 and 5
arr = np.random.randint(2,5, (3,4))
arr

array([[4, 3, 4, 3],
       [3, 2, 3, 4],
       [4, 3, 4, 3]], dtype=int32)

In [496]:
# Reshape the array to 2x3x2
arr.reshape(2, 3, -1)

array([[[4, 3],
        [4, 3],
        [3, 2]],

       [[3, 4],
        [4, 3],
        [4, 3]]], dtype=int32)

In [497]:
# .flatten - returns a 1D array of the elements in the array.
flat_arry = arr.flatten()
flat_arry

array([4, 3, 4, 3, 3, 2, 3, 4, 4, 3, 4, 3], dtype=int32)

In [498]:
# arr.sum(axis=0) # column wise sum
# arr.sum(axis=1) # row wise sum
# total sum of all elements in the array
arr.sum()

np.int64(40)

In [499]:
arr.sum(axis=0)

array([11,  8, 11, 10])

In [500]:
arr.sum(axis=1) 

array([14, 12, 14])

In [501]:
# row wise product of all elements in the array
arr.prod(axis = 1) 

array([144,  72, 144])

In [502]:
# cumulative sum along the column
arr.cumsum(axis =0) 

array([[ 4,  3,  4,  3],
       [ 7,  5,  7,  7],
       [11,  8, 11, 10]])

In [503]:
# .max - returns the maximum value in the array
arr.max()

np.int32(4)

In [504]:
# column wise minimum
arr.min(axis=0) 

array([3, 2, 3, 3], dtype=int32)

In [505]:
# column wise index of maximum value
arr.argmax(axis=0) 

array([0, 0, 0, 1])

In [506]:
arr1 = np.random.randint(1,3, (2,3))
arr2 = np.random.randint(1,3, (2,2))

In [507]:
arr1

array([[2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [508]:
arr2

array([[1, 2],
       [1, 2]], dtype=int32)

In [ ]:
# Row wise merging of two arrays
merged = np.concatenate((arr1, arr2), axis=1) 
merged

array([[2, 2, 1, 1, 2],
       [2, 2, 1, 1, 2]], dtype=int32)