## ✅ NumPy Operations
# Arithmetic Operations
 - Addition (+)
 - Subtraction (-)
 - Multiplication (*)
 - Division (/)
# Mathematical Functions
 - np.sqrt()
 - np.power()
 - np.exp()
 - np.log()
# Statistical Operations
 - sum()
 - mean()
 - std()
 - min(), max()
# Comparison Operations
 - >, <, ==, !=
# Logical Operations
 - np.logical_and()
 - np.logical_or()
 - np.logical_not()
# Array Manipulation
 - reshape()
 - flatten()
 - transpose() / .T
# Indexing and Slicing
 - Access elements (arr[i])
 - Slice arrays (arr[start:end])
# Broadcasting
 - Operations between arrays of different shapes
# Aggregation Operations
 - argmax(), argmin()
 - cumsum(), cumprod()
# Sorting and Searching
 - np.sort()
 - np.where()
 - np.unique()

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,6, (2,3))
b = np.random.randint(6,10, (3,3))
c = np.random.randint(1,9, (3,3))
a, b, c

(array([[3, 5, 3],
        [1, 1, 4]]),
 array([[7, 8, 9],
        [9, 6, 7],
        [7, 8, 6]]),
 array([[8, 8, 5],
        [5, 2, 7],
        [6, 8, 7]]))

# 1. Element Opeations

# Arithmetic Operations

In [3]:
# b + c
np.add(b,c) # element wise addition of two arrays

array([[15, 16, 14],
       [14,  8, 14],
       [13, 16, 13]])

In [4]:
# b - c
np.subtract(b,c) # element wise subtraction of two arrays

array([[-1,  0,  4],
       [ 4,  4,  0],
       [ 1,  0, -1]])

In [5]:
# b * c
np.multiply(b,c) # element wise multiplication of two arrays

array([[56, 64, 45],
       [45, 12, 49],
       [42, 64, 42]])

In [6]:
# b / c
np.round(np.divide(b,c), 2) # element wise division of two arrays

array([[0.88, 1.  , 1.8 ],
       [1.8 , 3.  , 1.  ],
       [1.17, 1.  , 0.86]])

In [7]:
# modulo
np.mod(b,c) # element wise modulo of two arrays
# b % c

array([[7, 0, 4],
       [4, 0, 0],
       [1, 0, 6]])

In [8]:
# a ** 2 # element wise exponentiation of an array with a scalar value
np.pow(a, 2) # element wise exponentiation of an array with a scalar value
# np.pow(b,c) # element wise exponentiation of two arrays

array([[ 9, 25,  9],
       [ 1,  1, 16]])

# Trignometric

In [9]:
np.sin(a)

array([[ 0.14112001, -0.95892427,  0.14112001],
       [ 0.84147098,  0.84147098, -0.7568025 ]])

In [10]:
cot = 1/np.tan(a)
cot

array([[-7.01525255, -0.29581292, -7.01525255],
       [ 0.64209262,  0.64209262,  0.86369115]])

# Rounding Operations

In [11]:
np.around(cot, 2)


array([[-7.02, -0.3 , -7.02],
       [ 0.64,  0.64,  0.86]])

In [12]:
np.floor(cot)

array([[-8., -1., -8.],
       [ 0.,  0.,  0.]])

In [13]:

np.ceil(cot)

array([[-7., -0., -7.],
       [ 1.,  1.,  1.]])

# Matrix Operations

In [14]:
a = np.random.randint(1,50, (2,3))
b = np.random.randint(6,100, (3,3))

In [15]:
a.shape

(2, 3)

In [16]:
b.shape

(3, 3)

In [17]:
# a @ b # matrix multiplication of two arrays
# np.dot(a,b) # matrix multiplication of two arrays
res = a.dot(b) # matrix multiplication of two arrays
res

array([[5590, 2843, 5775],
       [5540, 2681, 4923]])

In [18]:
res.shape

(2, 3)

In [19]:
# Inverse Matrix
det = np.linalg.det(b) # determinant of a matrix
det


np.float64(41261.99999999996)

In [20]:
np.linalg.inv(b) # inverse of a matrix

array([[ 0.04180602, -0.01272357, -0.04318744],
       [-0.10702341,  0.0760506 ,  0.08099462],
       [ 0.01672241, -0.01958218,  0.00591343]])