# NumPy Operations

In [46]:
import numpy as np

In [47]:
# a = np.random.randint(1,6, (2,3))
# b = np.random.randint(6,10, (3,3))
# c = np.random.randint(1,9, (3,3))
a = np.array([[2, 3, 2],
            [5, 3, 1]])

b = np.array([[7, 9, 8],
                 [7, 6, 6],
                 [6, 6, 7]]),

c = np.array([[7, 2, 3],
              [4, 1, 5],
              [2, 4, 6]])

a, b, c

(array([[2, 3, 2],
        [5, 3, 1]]),
 (array([[7, 9, 8],
         [7, 6, 6],
         [6, 6, 7]]),),
 array([[7, 2, 3],
        [4, 1, 5],
        [2, 4, 6]]))

In [48]:
np.round(np.sqrt(c), 2)

array([[2.65, 1.41, 1.73],
       [2.  , 1.  , 2.24],
       [1.41, 2.  , 2.45]])

In [49]:
np.pow(b, c)

array([[[823543,     81,    512],
        [  2401,      6,   7776],
        [    36,   1296, 117649]]])

In [50]:
# .exp() function is used to calculate the exponential of all elements in the input array.

np.round(np.exp(a), 2)

array([[  7.39,  20.09,   7.39],
       [148.41,  20.09,   2.72]])

In [51]:
# .log10() function is used to calculate the logarithm of all elements in the input array to the base 10.
np.round(np.log10(c), 2)

array([[0.85, 0.3 , 0.48],
       [0.6 , 0.  , 0.7 ],
       [0.3 , 0.6 , 0.78]])

In [52]:
np.sum(a)

np.int64(16)

In [53]:
np.sum(a, axis=0) # column wise sum

array([7, 6, 3])

In [54]:
# Returns the average of the array elements.
np.mean(a, axis=0)

array([3.5, 3. , 1.5])

In [55]:
# Returns the standard deviation, a measure of the spread of a distribution, of the array elements.
np.std(a, axis=0)

array([1.5, 0. , 0.5])

In [56]:
# Return the minimum of an array or minimum along an axis.
np.min(a, axis=0)

array([2, 3, 1])

In [57]:
np.max(a, axis=0)

array([5, 3, 2])

In [58]:
# condition 1: a == 1
# condition 2: a < 5
# Results: True if both conditions satisfied
np.logical_and(a == 1, a < 5)


array([[False, False, False],
       [False, False,  True]])

In [59]:
# True value where values are not 3 :  a != 3
# True only where a == 3 (reverse it) : logical_not
np.logical_not(a != 3)

array([[False,  True, False],
       [False,  True, False]])

In [60]:
# condition 1: a > 1
# condition 2: a < 5
# Results: True if any one condition satisfied
np.logical_or(a > 5, a < 5)

array([[ True,  True,  True],
       [False,  True,  True]])

In [ ]:
# reshape is use to re-size the array size (rows and columns)
a.reshape(2, 3)

array([[2, 3, 2],
       [5, 3, 1]])

In [ ]:
# flatten function makes 1d array list
a.flatten()

array([2, 3, 2, 5, 3, 1])

In [ ]:
# Transpose reverse the rows into columns and vice-versa
Transpose = a.T
Transpose

array([[2, 5],
       [3, 3],
       [2, 1]])

In [ ]:
# Accessing the element using the indexing. [row, column]
a

array([[2, 3, 2],
       [5, 3, 1]])

In [96]:
a[-1,-1]

np.int64(1)

In [99]:
# Slicing is use to get multiple elements (sub array) by (Start:End:Steps)
a[0:1]

array([[2, 3, 2]])

In [ ]:
# Return the index (position) of maximum values (not the value itself)
a.argmax()

np.int64(3)

In [ ]:
# Return the index (position) of minimum values (not the value itself)
a.argmin()

np.int64(5)

In [ ]:
# Adds elements step-by-step
a.cumsum()

array([ 2,  5,  7, 12, 15, 16])

In [ ]:
# Multiplies elements step-by-step
a.cumprod()

array([  2,   6,  12,  60, 180, 180])

In [ ]:
# Sorts array elements in ascending order
np.sort(a)

array([[2, 2, 3],
       [1, 3, 5]])

In [ ]:
# Finds indices where a condition is true
np.where(a > 0)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [ ]:
# Returns unique (non-repeated) values
np.unique(a)

array([1, 2, 3, 5])